replicaCount: 1

image:
  repository: "ravula1246/springboot"
  tag: "1.0.0"  # Specify the exact version tag
  pullPolicy: IfNotPresent

service:
  name: springboot
  type: ClusterIP  
  port: 8080

env:
  SPRING_PROFILES_ACTIVE: "prod"  

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"
