apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: springboot-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
