apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: springboot
